// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsSzuof0sWi0Ws3QyUVg8eb5GVZYsLAp4',
    appId: '1:520954394142:web:3ad5387c88736c7adda00f',
    messagingSenderId: '520954394142',
    projectId: 'runup-f5c63',
    authDomain: 'runup-f5c63.firebaseapp.com',
    storageBucket: 'runup-f5c63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXzfTiFHxScxWN1e3VpY8cn3qPxjSHPk',
    appId: '1:520954394142:android:fd2aeba2dc58e4c7dda00f',
    messagingSenderId: '520954394142',
    projectId: 'runup-f5c63',
    storageBucket: 'runup-f5c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDboSThjKkWC81AW-xzPeFOxfRW_l6iKYw',
    appId: '1:520954394142:ios:7e940ff703c43092dda00f',
    messagingSenderId: '520954394142',
    projectId: 'runup-f5c63',
    storageBucket: 'runup-f5c63.firebasestorage.app',
    iosClientId: '520954394142-a3jmqbu0meagsalientalpgiapo21usg.apps.googleusercontent.com',
    iosBundleId: 'com.example.runup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDboSThjKkWC81AW-xzPeFOxfRW_l6iKYw',
    appId: '1:520954394142:ios:7e940ff703c43092dda00f',
    messagingSenderId: '520954394142',
    projectId: 'runup-f5c63',
    storageBucket: 'runup-f5c63.firebasestorage.app',
    iosClientId: '520954394142-a3jmqbu0meagsalientalpgiapo21usg.apps.googleusercontent.com',
    iosBundleId: 'com.example.runup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsSzuof0sWi0Ws3QyUVg8eb5GVZYsLAp4',
    appId: '1:520954394142:web:eccfade4c5a8f535dda00f',
    messagingSenderId: '520954394142',
    projectId: 'runup-f5c63',
    authDomain: 'runup-f5c63.firebaseapp.com',
    storageBucket: 'runup-f5c63.firebasestorage.app',
  );
}
